### ISSUE TITLE
Rotary Encoder - no INPUT_PULLDOWN possible

### ISSUE THREAD

**Issue by erniberni** [biologist79/Tonuino-ESP32-I2S#25]
I am not sure if this really matters.
The GPIO34 and GPIO35 where the rotary encoder is connected has no sw enable pullup or pulldown.
The used library ESP32Encoder default enables a pulldown on these GPIOs but this is not working.

**Comment by biologist79** [comment]
Didn't have any problems so far. Encoder's button is pulled internally (in the encoder) to high if not pressed.

**Comment by tueddy** [comment]
I can confirm the encoder works without any problems.

**Comment by tueddy** [comment]
This could be the reason why it works flawless:

![Keyes-KY-040-Rotary-Encoder-Module-Schematic](https://user-images.githubusercontent.com/11274319/102658323-a4feae80-4177-11eb-911f-c156088e0cf5.png)

If you put just the rotary encoder on a PCB you should use external pullups. For the breakout module it works because resistors are already on the module.

**Comment by erniberni** [comment]
Yes, I am sure, this is the reason. I am using an encoder like this https://www.amazon.de/Rotary-Encoder-Schalter-Drehschalter-Keyswitch/dp/B0085I4D5C/
That type has no pullups. I used an external pulldown, because the library ESP32Encoder is expecting pulldowns as default. I think this doesn't really matter, if the sw is detecting signal edges.
